config/routes.rb
Rails.application.routes.draw do
  resources :payment_notifications
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    root "products#index"
    resources :carts
    resources :cart_items
    resources :products
    resources :searches
    resources :categories
    resources :letters
    get 'current_cart', action: :show, controller: 'carts'
    #current_cart 'cart', :controller => 'carts', :action => 'show'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.ht
  end
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '', to: redirect("/#{I18n.default_locale}")
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :cart_items
	has_many :products, :through => :cart_items
	
	def total_price
		cart_items.to_a.sum(&:full_price)
	end




  def paypal_encrypted(return_url, notify_url)
    values = {
      :business => APP_CONFIG[:paypal_email],
      :cmd => '_cart',
      #:cmd => "_s-xclick",
      :upload => 1,
      :return => return_url,
      :invoice => id,
      :notify_url => notify_url,
      :cert_id =>'E5FAYYTHZYYGA'
      #:cert_id => APP_CONFIG[:paypal_cert_id]
    }
    cart_items.each_with_index do |item, index|
      values.merge!({
        "amount_#{index+1}" => item.unit_price,
        "item_name_#{index+1}" => item.product.name,
        "item_number_#{index+1}" => item.id,
        "quantity_#{index+1}" => item.quantity
      })
    end
    encrypt_for_paypal(values)
  end

  PAYPAL_CERT_PEM = File.read("#{Rails.root}/certs/paypal_cert.pem")
  APP_CERT_PEM = File.read("#{Rails.root}/certs/app_cert.pem")
  APP_KEY_PEM = File.read("#{Rails.root}/certs/app_key.pem")

  def encrypt_for_paypal(values)
    signed = OpenSSL::PKCS7::sign(OpenSSL::X509::Certificate.new(APP_CERT_PEM), OpenSSL::PKey::RSA.new(APP_KEY_PEM, ''), values.map { |k, v| "#{k}=#{v}" }.join("\n"), [], OpenSSL::PKCS7::BINARY)
    OpenSSL::PKCS7::encrypt([OpenSSL::X509::Certificate.new(PAYPAL_CERT_PEM)], signed.to_der, OpenSSL::Cipher::Cipher::new("DES3"), OpenSSL::PKCS7::BINARY).to_s.gsub("\n", "")
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	@cart  = current_cart
  end

  def edit
    @cart = current_cart
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/edit.html.erb
<% title "Edit page" %>

<h1>Editting Shopping Cart</h1>


<% title "Cart" %>


  <tr>
    <td class="total price" colspan="4">
      Total: <%= number_to_currency @cart.total_price %>
    </td>
  </tr>
</table>

<p>
  <% if session[:last_product_page] %>
    <%= link_to "Continue Shopping", session[:last_product_page] %> |
  <% end %>
  <%= link_to "Checkout" %>
</p>

app/views/carts/show.html.erb
<% title "Cart" %>

<table id="cart_items">
  <tr>
    <th>Product</th>
    <th>Qty</th>
    <th class="price">Unit Price</th>
    <th class="price">Full Price</th>
  </tr>
  <% for cart_item in @cart.cart_items %>
    <% if cart_item.product  %>
    <tr class="<%= cycle :odd, :even %>">
      <td><%=h cart_item.product.name %></td>
      <td class="qty"><%= cart_item.quantity %></td>
      <td class="price"><%= number_to_currency(cart_item.unit_price) %></td>
      <td class="price"><%= number_to_currency(cart_item.full_price) %></td>
    </tr>
  <% end %>
  <% end %>
  <tr>
    <td class="total price" colspan="4">
      Total: <%= number_to_currency @cart.total_price %>
    </td>
  </tr>
</table>



<p>
   <%= link_to "Continue Shopping", products_path %>
</p>

<%= form_tag APP_CONFIG[:paypal_url] do %>
  <%= hidden_field_tag :cmd, "_s-xclick" %>
  <%= hidden_field_tag :encrypted, @cart.paypal_encrypted(products_url, payment_notifications_url(:secret => APP_CONFIG[:paypal_secret])) %>
  <%= submit_tag "Checkout" %>
<% end %>