config/routes.rb
Rails.application.routes.draw do
  resources :payment_notifications
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    root "products#index"
    resources :carts
    resources :cart_items
    resources :products
    resources :searches
    resources :categories
    resources :letters
    get 'current_cart', action: :show, controller: 'carts'
    #current_cart 'cart', :controller => 'carts', :action => 'show'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.ht
  end
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '', to: redirect("/#{I18n.default_locale}")
end

app/models/letter.rb
class Letter
    include ActiveModel::Model
    attr_reader :char

  def self.all
    ('A'..'Z').map { |c| new(c) }
  end
  
  def self.find(param)
    self.all.detect { |l| l.to_param == param } || raise(ActiveRecord::RecordNotFound)
  end
  
  def initialize(char)
    @char = char
  end
  
  def to_param
    @char.downcase
  end
  
  def products
    #Product.find(:all, :conditions => ["name LIKE ?", @char + '%'], :order => "name")
    Product.all.where(["name LIKE ?", @char + '%']).order(:name)

  end
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController

	def index
	  @letters = Letter.all
	end

	def show
	  @letter = Letter.find(params[:id])
	end

end

app/helpers/letters_helper.rb
module LettersHelper
end

app/views/letters/index.html.erb
<% title " Select a letter" %>

<h1>Select a letter </h1>

<% @letters.each do |letter| %>
	<%= link_to letter.char, letter_path(letter) %>
<% end %>

app/views/letters/show.html.erb
<% title "Products for Letter #{@letter.char}" %>

<p><%= link_to "Select a Letter", letters_path %></p>

<%= render :partial => @letter.products %>

app/views/letters/show.js.erb
$('#products').append('<%= j render(@products) %>');
<% if @products.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@products) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>