config/routes.rb
Rails.application.routes.draw do
  resources :payment_notifications
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    root "products#index"
    resources :carts
    resources :cart_items
    resources :products
    resources :searches
    resources :categories
    resources :letters
    get 'current_cart', action: :show, controller: 'carts'
    #current_cart 'cart', :controller => 'carts', :action => 'show'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.ht
  end
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '', to: redirect("/#{I18n.default_locale}")
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	has_many :cart_items

	def self.search(search)
		if search
			self.all.order(:name).where(['name LIKE ?', "%#{search}%"])
		else
			self.all
		end
	end

	def category_name
		category.try(:name)
	end

	def category_name=(name)
		self.category = Category.find_or_create_by(name: name) if name.present?
	end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    # @products = Product.order("name").page(params[:page]).per_page(5)
    @products = Product.search(params[:search]).page(params[:page]).per_page(10)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, :notice => "Successfully created product."
    else
      render :action => 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to @product, :notice  => "Successfully updated product."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url, :notice => "Successfully destroyed product."
  end

  private

  def product_params
    params.require(:product).permit(:price, :name, :description, :released_at, :category_id, :category_name)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
     <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>


  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :released_at %><br />
    <%= f.date_select :released_at %>
  </div>
  <div class="field">
    <%= f.label :category_name %><br />

    <!-- client side rendering, good for small database driven application
      <% f.text_field :category_name, data: {autocomplete_source: Category.order(:name).map(&:name)} %>
      -->

    <!-- server side rendering -->
    <%= f.text_field :category_name, data: {autocomplete_source: categories_path} %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
    <div class="product">
      <h2><%= link_to product.name, product %></h2>

      <div class="details">
       <%= Product.human_attribute_name(:price) %> :
        <%= number_to_currency(product.price) %> |
        <% if product.released_at? %>
              Released on <%= product.released_at.strftime("%B %e, %Y") %>
         <% else %>
          Comming Soon
         <% end %>
      </div>
    
    <%= Product.human_attribute_name(:category) %>: <%=h product.category.name %>

      <div class="actions">
        <%= link_to "Add to Cart", cart_items_path(:product_id => product), :method => :post %>
      </div>
    </div>

app/views/products/_simple_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1><%= t '.title' %></h1>

<em><%= t '.description' %></em>

<%= form_tag products_path, :method => 'get' do  %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>


<%= link_to "Advanced Search", new_search_path %>

<div id="products">
  <%= render @products %>
</div>

<p><%= link_to "New Product", new_product_path %></p>

<%= will_paginate @products, previous_label: h("Previous"), next_label: h("Next") %>

app/views/products/index.js.erb
$('#products').append('<%= j render(@products) %>');
<% if @products.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@products) %>');
<% else %>
  $('.pagination').remove();
<% end %>

<% sleep 1 %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<%= simple_format h(@product.description) %>

<p>
  <b><%= Product.human_attribute_name(:price) %>:</b>
  <%= number_to_currency @product.price %>
</p>

<%= link_to "Add to Cart", cart_items_path(:product_id => @product, :unit_price => @product.price), :method => :post %>

<p>
  <b>Released at:</b>
  <%= @product.released_at %>
</p>

<% unless @product.category.nil? %>
<p>
  <strong>Category:</strong>
  <%= @product.category.name %>
</p>
<% end %>

<p>
  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'All Products', products_path %>
</p>